// <auto-generated />
using System;
using Axiom.Services.PersonAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Axiom.Services.PersonAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240730122203_addHealthDetails")]
    partial class addHealthDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Axiom.Services.PersonAPI.Models.HealthDetails", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActivityTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergiesList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Considerations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DoExercises")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HadRecentSurgery")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HasAllergies")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HasProsthesisPinPlate")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HighRiskPregnancy")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MakesRepetitiveMovement")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MedicalTreatment")
                        .HasColumnType("tinyint");

                    b.Property<string>("MedicationsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Pregnant")
                        .HasColumnType("tinyint");

                    b.Property<int>("PressureLevel")
                        .HasColumnType("int");

                    b.Property<string>("ProsthesisPinPlateList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecentSurgeryList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TakingContinuousMedication")
                        .HasColumnType("tinyint");

                    b.Property<string>("TreatmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeeklyFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeeksPregnant")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("HealthDetails");
                });

            modelBuilder.Entity("Axiom.Services.PersonAPI.Models.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonId"));

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocuppation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PersonDetails", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreferredTechniques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferredTouchPressure")
                        .HasColumnType("int");

                    b.Property<bool>("ReceivedProfessionalMassage")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceExpectations")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("PersonDetails");
                });

            modelBuilder.Entity("Axiom.Services.PersonAPI.Models.HealthDetails", b =>
                {
                    b.HasOne("Axiom.Services.PersonAPI.Models.Person", "Person")
                        .WithOne("HealthDetails")
                        .HasForeignKey("Axiom.Services.PersonAPI.Models.HealthDetails", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonDetails", b =>
                {
                    b.HasOne("Axiom.Services.PersonAPI.Models.Person", "Person")
                        .WithOne("PersonDetails")
                        .HasForeignKey("PersonDetails", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Axiom.Services.PersonAPI.Models.Person", b =>
                {
                    b.Navigation("HealthDetails")
                        .IsRequired();

                    b.Navigation("PersonDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
